### ISSUE TITLE
Support ONVIF back channels

### ISSUE THREAD

**Issue by chao-camect** [bluenviron/gortsplib#101]
See section 5.3 of https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf

**Comment by chao-camect** [comment]
I found a way to do it, use Client.OnRequest to modify to reques to get backchannel.

**Comment by theblazehen** [comment]
@chao-camect I'd appreciate a code sample if you have one!

**Comment by SijmenHuizenga** [comment]
@chao-camect comment on using `OnRequest` helped me figure this out. So for whoever stumbles across this issue here are some extra clues:

Tell the rtsp server that backchanneling is required:
```
&gortsplib.Client{
                ....
		OnRequest: func(r *base.Request) {
			r.Header["Require"] = []string{"www.onvif.org/ver20/backchannel"}
		},
	}
```
Probably only needed during `Describe` request but sending the header on every request works as well.

One of the Tracks returned is the backchannel. No idea how to properly find the correct one, on my camera it is always the last channel so i just take the last one.

After `SetupAndPlay`, send packets using `rtspClient.WritePacketRTP`

**Comment by aler9** [comment]
Hello all, in order to support ONVIF back channels, the following improvements are required:

* medias must preserve the `recvonly`, `sendonly` or `sendrecv` attribute in order to allow identification of back channels
* in the client, DESCRIBE and SETUP requests must contain `www.onvif.org/ver20/backchannel` (as already pointed out by @SijmenHuizenga )
* in the client, tests must be added in order to ensure that `WritePacketRTP()` works with these tracks
* in the server, `recvonly` tracks must be hidden, at least for the moment. This is somewhat linked to https://github.com/aler9/rtsp-simple-server/issues/216 - when we are proxying a stream, should we allow clients to send commands to the original stream? what happens if clients are more than one? should we allow a single of them to influence all the other ones?

**Comment by RogerHardiman** [comment]
Hi.
Just a quick hello from the Yellowstone project. A NodeJS RTSP Client library.
We recently had a contribution to add Audio BackChannel to Yellowstone which is now in the master branch. The contribution opens an alaw audio file and generates the RTP payloads and sends them to the camera.
I just completed a code review and clean up of the contribution and it is all in the master branch.

I'm using it with an Axis Camera and it works well.

Note the author who raised a PR on Yellowstone only wrote the code for sending the RTP audio packets over a TCP connection (RTP embedded in the RTSP stream) rather than sending via UDP so that is still to add at some point.

But this may be handy for this project for testing.

**Comment by nu774** [comment]
Hi, if this library is to support bi-directional (sendrecv) streaming, these lines should also be fixed:
https://github.com/bluenviron/gortsplib/blob/main/client.go#L711
https://github.com/bluenviron/gortsplib/blob/main/server_session.go#L834
These lines assume one-way media flow and the other way round for RTCP feedback only. 8 is too small  
 for bi-directional streaming, and currently the number is not configurable from user.

**Comment by cedricve** [comment]
Any idea to work further on this?
