### ISSUE TITLE
Grandstream GXV3500 RTSP viewer wants a:control=trackID

### ISSUE THREAD

**Issue by RogerHardiman** [bluenviron/gortsplib#190]
Hi
Grandstream make a hardware box that receives RTSP and outputs video on an attached monitor.
It does not work with rtsp-simple-server so I did some debugging.
Looking at the syslog messages the GXV3500 produces, it seems to want the 'a:control=' item in the SDP to use "trackID=x" and not "mediaUUID=xxx" as the syslog error says "trackID not found in a:control"

So a buggy RTSP client from Grandstream that is looking for trackID=n

So I'm going to have a go changing gortsplib and swapping the hard coded 'mediaUUID' to 'trackID' instead and see what it does.

So just posting this in case someone else hits the problem, or someone else has already made a patch or fork.

Thanks
Roger Hardman

**Comment by aler9** [comment]
Hello, `trackID=[something]` was changed into `mediaID=[random UUID]` for two reasons:

* to better portray the specification, that doesn't talk about tracks but talks about "media streams" that contain one or more formats
* to normalize incoming streams, that are sent by a wide variety of clients, each with a different (and sometimes conflicting) control attribute, that before the change was passed as-is

In my opinion the Grandstream client should have been developed in a more versatile way, since this behavior is not compatible with half of available cameras, but anyway, it's not a big deal to support it.

I'll edit the library in order to use `trackID=[increasing_number]`, in order to restore compatibility and at the same time normalize incoming streams.

**Comment by RogerHardiman** [comment]
Hi
I agree, it is a stupid client. The client (grandstream) told me they only do interop testing with a few devices, their own kit, and another CCTV device that also happened to trackID=nn
I was happy to have my own local Patch for this, I'd just not gotten around to making it and testing it.

**Comment by aler9** [comment]
added in MediaMTX v0.22.1
