### ISSUE TITLE
invalid key: c (c=IN IP4 0.0.0.0)

### ISSUE THREAD

**Issue by yangchao2015** [bluenviron/gortsplib#288]
![00099595a1ea07c3d2e5ed566a9011f](https://github.com/bluenviron/gortsplib/assets/11486388/ba381e9d-945a-4559-af03-0353b9d7cfaa)
RTSP拉流时，出现错误提示导致拉流失败，错误信息为：invalid key: c (c=IN IP4 0.0.0.0)，可能为SDP问题，希望可以处理解决

**Comment by aler9** [comment]
Hello, can you write the model and vendor of the camera?

**Comment by yangchao2015** [comment]
您好，您的邮件已收到，谢谢！

**Comment by yangchao2015** [comment]
我对接的是海康的流媒体平台，设备型号和品牌比较多

**Comment by yangchao2015** [comment]
![1684984862708](https://github.com/bluenviron/gortsplib/assets/11486388/f0e2d412-eb99-4212-8fbb-18b38bdd2b17)
这个是通过VLC播放的媒体信息

**Comment by aler9** [comment]
In order to solve this issue, we need the SDP from the camera or the HikVision platform, that can be obtained, for example, in this way:

Download [MediaMTX](https://github.com/bluenviron/mediamtx) and configure it to pull the stream of the camera/platform. Set `logLevel` to `debug`. Wait for the error to appear. Close the software. Post the entire log.

**Comment by yangchao2015** [comment]
您好，您的邮件已收到，谢谢！

**Comment by aler9** [comment]
closed since required data was not provided.

**Comment by yangchao2015** [comment]
您好，您的邮件已收到，谢谢！
