### ISSUE TITLE
Need to eliminate incorrect SDP

### ISSUE THREAD

**Issue by FireTiger23** [bluenviron/gortsplib#381]
There is a device that, after restarting, the SDP of the stream is incorrect, and the stream can be pulled normally, but there is no picture playing

Correct SDP
![image](https://github.com/bluenviron/gortsplib/assets/6301010/d886af28-a2f6-44d0-a244-49753040be73)

Abnormal SDP

![image](https://github.com/bluenviron/gortsplib/assets/6301010/cacaca28-92a0-422d-b834-9a8337afedce)

SDP incorrect, streamed successfully, no screen played。

Can we discard this SDP and return a failure for the client to pull the stream again

**Comment by aler9** [comment]
Hello,
You're perfectly right about checking the consistency of incoming tracks, the problem is that there are a lot of metadata tracks that are advertised in a way very similar to the one of the invalid video track you posted, and these tracks are valid.

I'll add a consistency check on non-metadata tracks, but if it causes troubles i'll be forced to perform a roll-back.
