### ISSUE TITLE
Nalu frame decoding issue.

### ISSUE THREAD

**Issue by cmpeguerog** [bluenviron/gortsplib#641]
Im having issues decoding nalu packages from a Drone simulator using [client-play-format-h265-convert-to-jpeg](https://github.com/bluenviron/gortsplib/tree/22426c2f18512045a28577d9d769ffe176c84688/examples/client-play-format-h265-convert-to-jpeg) example. The server name returned with **ffprobe** with loglevel set to trace is **Server: gortsplib** is possible that the RTSP source uses this library or a fork of the same?. I attached the ffprobe output as well the decoded images and the program output.

1. [example output.txt](https://github.com/user-attachments/files/17527128/example.output.txt)
2. [Decoded Image #1](https://github.com/user-attachments/assets/f8e5639e-3036-4398-9860-68e2d7fc859e)
3. [Decoded Image #2](https://github.com/user-attachments/assets/baba3e30-8885-48b2-9d26-c7e30ad698f2)
4. [Decoded Image #3](https://github.com/user-attachments/assets/54879ebd-16a0-46a8-974b-f10e8b6fc479)
5. [Decoded Image #4](https://github.com/user-attachments/assets/65d4d8f8-430f-48d7-9c9e-433d0fb8e246)
6. [Decoded Image #5](https://github.com/user-attachments/assets/600d4f7b-8fa7-454e-9966-029cd165b938)
7. [ffprobe output](https://github.com/user-attachments/files/17527117/output.txt)

**Comment by aler9** [comment]
Hello, the only thing that i can say regarding the images you provided is that H264 access units are being truncated somewhere after the encoding process. It's impossible to understand if this is caused by a bug in the library, by a bug in the software that is using this library or by a misconfiguration in one of the involved components.
